# Generated by Django 2.2.6 on 2019-10-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotaçõeshospedemodels',
            name='valor',
        ),
    ]
