# Generated by Django 2.2.6 on 2019-10-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0002_remove_cotaçõeshospedemodels_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='textowhatsappmodels',
            name='check_in',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='textowhatsappmodels',
            name='check_out',
            field=models.DateField(default=None),
        ),
    ]
